CREATE TABLE PAYMENT_CHANNELS
(
    PAYMENT_CHANNEL_ID    BIGINT,
    NAME                  VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (PAYMENT_CHANNEL_ID)
);

CREATE SEQUENCE PAYMENT_CHANNEL_ID_SEQ START 1 INCREMENT 1;
