CREATE TABLE PAYMENTS
(
    PAYMENT_ID            BIGINT,
    EXTERNAL_ID           BIGINT NOT NULL UNIQUE,
    PAYMENT_DATE          DATE,
    PAYMENT_CHANNEL_ID    BIGINT,
    SUBSCRIBER_ID         BIGINT,
    AMOUNT                REAL,
    PERIOD                VARCHAR(255),
    COMMENT               VARCHAR(255),
    PRIMARY KEY (PAYMENT_ID)
);

CREATE SEQUENCE PAYMENT_ID_SEQ START 1 INCREMENT 1;
