CREATE TABLE STREETS
(
    STREET_ID             BIGINT,
    EXTERNAL_ID           BIGINT NOT NULL UNIQUE,
    NAME                  VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (STREET_ID)
);

CREATE SEQUENCE STREET_ID_SEQ START 1 INCREMENT 1;
