CREATE TABLE CHARGE_TARGETS
(
    CHARGE_TARGET_ID      BIGINT,
    NAME                  VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (CHARGE_TARGET_ID)
);

CREATE SEQUENCE CHARGE_TARGET_ID_SEQ START 1 INCREMENT 1;
