CREATE TABLE SUBSCRIBERS
(
    SUBSCRIBER_ID         BIGINT,
    EXTERNAL_ID           BIGINT NOT NULL UNIQUE,
    FIRSTNAME             VARCHAR(255) NOT NULL,
    PATRONYMIC            VARCHAR(255),
    LASTNAME              VARCHAR(255) NOT NULL,
    CONTRACT_NUMBER       VARCHAR(255) UNIQUE,
    ACCOUNT_NUMBER        VARCHAR(255) UNIQUE,
    CITY_ID               BIGINT,
    STREET_ID             BIGINT,
    HOUSE                 INTEGER,
    FLAT                  INTEGER,
    PHONE_NUMBER          VARCHAR(255) NOT NULL,
    EMAIL                 VARCHAR(255) NOT NULL,
    BALANCE               REAL,
    IS_ACTIVE             BOOLEAN,
    CONNECTION_DATE       DATE,
    PRIMARY KEY (SUBSCRIBER_ID)
);

CREATE SEQUENCE SUBSCRIBER_ID_SEQ START 1 INCREMENT 1;
