CREATE TABLE NOTIFICATIONS
(
    NOTIFICATION_ID       BIGINT,
    SENT_DATE             TIMESTAMP,
    SUBSCRIBER_ID         BIGINT,
    STATUS                VARCHAR(255) NOT NULL,
    CHANNEL               VARCHAR(255) NOT NULL,
    MESSAGE               VARCHAR(255) NOT NULL,
    DESTINATION           VARCHAR(255) NOT NULL,
    REASON                VARCHAR(255),
    PRIMARY KEY (NOTIFICATION_ID)
);

CREATE SEQUENCE NOTIFICATION_ID_SEQ START 1 INCREMENT 1;
