server:
  port: 8250

spring:
  application:
    name: report-generator
  config:
    import: configserver:http://localhost:8220

  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml

